name: Bot do Brasileirao ETL

on:
  schedule:
    # Roda todos os dias às 09:00 da manhã (Horário de Brasília)
    - cron: '0 12 * * *'
  
  # Este comando cria um botão no GitHub para você rodar manualmente quando quiser
  workflow_dispatch: 

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: 📂 Puxando o código do repositório
      uses: actions/checkout@v3

    - name: 🐍 Configurando o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Instalando as bibliotecas
      run: |
        pip install -r requirements.txt

    - name: 🚀 Rodando a Pipeline ETL (Python)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      run: python etl_cartola.py

    - name: ⚙️ Gerando o profiles.yml dinamicamente
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python -c "
        import os
        from urllib.parse import urlparse
        
        url = urlparse(os.environ['DATABASE_URL'])
        schema = 'public' # Ajuste para o seu schema do Supabase, se for diferente
        
        profile = f'''
        brasileirao_dbt:
          target: dev
          outputs:
            dev:
              type: postgres
              host: {url.hostname}
              user: {url.username}
              password: {url.password}
              port: {url.port}
              dbname: {url.path[1:]}
              schema: {schema}
              threads: 4
        '''
        with open('profiles.yml', 'w') as f:
            f.write(profile)
        "

    - name: 🏗️ Rodando as transformações do dbt
      run: |
        dbt build --project-dir brasileirao_dbt --profiles-dir .
        # dbt_build é um comando que executa todas as etapas do dbt: run, test, snapshot e seed. Ele é útil para pipelines de CI/CD, pois garante que todas as transformações e testes sejam executados em sequência.